# Generated by Django 5.2 on 2025-04-23 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'blank': 'نام نباید خالی باشد'}, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_name', message='در نام از کاراکتر های \\ / <> " \' استفاده نکنید', regex='^(?!.*[<>"\\\'\\\\\\/]).+$')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'blank': 'نام خانوادگی نباید خالی باشد'}, max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_name', message='در نام از کاراکتر های \\ / <> " \' استفاده نکنید', regex='^(?!.*[<>"\\\'\\\\\\/]).+$')], verbose_name='نام خانوادگی'),
        ),
    ]
