# Generated by Django 5.2 on 2025-04-23 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'نام سفارش نمی\u200cتواند خالی باشد.', 'max_length': 'نام سفارش نباید بیشتر از ۲۵۵ کاراکتر باشد.'}, max_length=255, verbose_name='نام سفارش')),
                ('count', models.PositiveIntegerField(error_messages={'blank': 'تعداد نمی\u200cتواند خالی باشد.', 'invalid': 'تعداد باید یک عدد صحیح مثبت باشد.'}, verbose_name='تعداد')),
                ('total_price', models.DecimalField(decimal_places=2, error_messages={'blank': 'قیمت کل نمی\u200cتواند خالی باشد.', 'invalid': 'قیمت کل باید عددی معتبر باشد.'}, max_digits=12, verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('view_all_orders', 'دسترسی مشاهده همه سفارش\u200cها'), ('edit_all_orders', 'دسترسی ویرایش همه سفارش\u200cها'), ('delete_all_orders', 'دسترسی حذف همه سفارش\u200cها'), ('filter_all_orders', 'دسترسی فیلتر کردن سفارش\u200cها')],
            },
        ),
    ]
