# Generated by Django 5.2 on 2025-04-23 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(error_messages={'blank': 'نام سفارش نمی\u200cتواند خالی باشد.', 'max_length': 'نام سفارش نباید بیشتر از ۲۵۵ کاراکتر باشد.'}, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_name', message='در نام از کاراکتر های \\ / <> " \' استفاده نکنید', regex='^(?!.*[<>"\\\'\\\\\\/]).+$')], verbose_name='نام سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(error_messages={'blank': 'قیمت کل نمی\u200cتواند خالی باشد.', 'invalid': 'قیمت کل باید عددی معتبر باشد.'}, verbose_name='قیمت کل'),
        ),
    ]
