# Generated by Django 5.2 on 2025-04-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_name_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_orders', 'دسترسی مشاهده همه سفارش\u200cها'), ('edit_all_orders', 'دسترسی ویرایش همه سفارش\u200cها'), ('delete_all_orders', 'دسترسی حذف همه سفارش\u200cها')], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
    ]
